apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: feedback-enabled-public-profile
  description: Manish's Social Profile
  annotations:
    github.com/project-slug: mvsn98/FEPP
spec:
  type: service
  lifecycle: production
  owner: team-mv

