apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: feedback-enabled-public-profile
  description: Manish's Social Profile
  annotations:
    github.com/project-slug: mvsn98/FEPP
    backstage.io/techdocs-ref: dir:.
spec:
  type: Service
  lifecycle: production
  owner: team-mv
  jenkins:
    baseUrl: http://45.198.13.52:8080
    username: "Manish"
    apiToken: "11dcb1fc463b872dad09f958d73f925841"
    job: FEPP
    branch: main
  providesApis: [admin-panel, API:social-profile, API:feedback]
  consumesApis: [API:facebook-profile-photos]
  dependsOn: [resource:mongodb]
  dependencyOf: [resource:mv-portal]
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: admin-panel
spec:
  type: API
  lifecycle: production
  owner: team-mv
  definition:
    $text: https://github.com/mvsn98/FEPP/blob/main/catalog-info.yaml
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: social-profile
spec:
  type: API
  lifecycle: production
  owner: team-mv
  definition:
    $text: https://github.com/mvsn98/FEPP/blob/main/catalog-info.yaml
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: feedback
spec:
  type: API
  lifecycle: development
  owner: team-mv
  definition:
    $text: https://github.com/mvsn98/FEPP/blob/main/catalog-info.yaml
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: facebook-profile-photos
spec:
  type: API
  lifecycle: production
  owner: team-mv
  definition:
    $text: https://github.com/mvsn98/FEPP/blob/main/catalog-info.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: mongodb
spec:
  type: Database
  lifecycle: production
  owner: team-mv
  definition:
    $text: https://github.com/mvsn98/FEPP/blob/main/catalog-info.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: mv-portal
spec:
  type: My-Portal
  lifecycle: production
  owner: team-mv
  definition:
    $text: https://github.com/mvsn98/FEPP/blob/main/catalog-info.yaml
